### PR TITLE
[WIP] Remove redux form

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?

Remove redux-form
- this also removes validation so will need to fix this on another branch
 closes https://github.com/ServiceInnovationLab/pancake-frontend/issues/429

# How to test this change
Go into the code and find any Component starting with `<Field`
These are all using redux-form and should be removed or replaced with component name ie:

`<Field component={MyComponent} />` should be `<MyComponent />`

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] tested in Chrome
- [ ] tested in Firefox
- [ ] tested in IE
- [ ] tested in Safari
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

**Comment by dlouise64** [comment]
@Br3nda @ssibbehh I didnt factor in validations which is tied to redux-form so will create another ticket for this

**Comment by Br3nda** [comment]
@dlouise64 is this ready for review?

**Comment by Br3nda** [comment]
When you're ready, can you remove the "WIP" and then use github request review functionality

**Comment by Br3nda** [comment]
@dlouise64 okay to close this? We can keep the branch, and look again another time.

**Pull request closed without merging**
