### PR TITLE
Feature/privacy statement

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?
Added privacy statement link in footer
This opens a modal which contains the privacy statement

# How to test this change

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] tested in Chrome
- [ ] tested in Firefox
- [ ] tested in IE
- [ ] tested in Safari
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

**Comment by Br3nda** [comment]
the sentence "Privacy statement reviewed and approved by law" shouldn't be there

**Comment by Br3nda** [comment]
After viewing the privacy statement, then pressing close, i can no longer scroll anywhere.

**Comment by dlouise64** [comment]
@Br3nda Good catch. Fixed it.

**Comment by dlouise64** [comment]
@Br3nda this one has been sitting here for awhile. I've made the changes, unless there was something else you spotted?

**Comment by Br3nda** [comment]
I've turned off circle-ci for this project.

**Pull request merged**
