### PR TITLE
prevent user from typing commars in wage or salary income field

### LINKED ISSUE #502: Comma functionality with income $$
System – OS X 10.8.5
Processor 2.66 GHz Intel Core 2 Duo
Memory – 8GB 1067 MHz DDR3
Browser: Chrome Version 49.0.2623.112 (64-bit)

Went to add income and used a comma to do this.  Income calculation for salary and wages not included in total (no comma’s allowed):
image

Was able to apply and exit. Got email.

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?

closes #502 

Added check if income is a number
Refactored duplicate methods.

# How to test this change
Fill out form on first page.
On the second page, scroll to the income section, select 'Wage or Salary' and test that commars can not be typed in the input field.

Also make sure we cannot enter negative values

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] tested in Chrome
- [ ] tested in Firefox
- [ ] tested in IE
- [ ] tested in Safari
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

**Comment by Br3nda** [comment]
@dlouise64 this change a number like "30,000" into 30000. It seems to me this code could have a unit test for doing so - that it removes the comma, and that it adds up correctly.

**Comment by Br3nda** [comment]
Still infinite looping 
image

**Comment by Br3nda** [comment]
The infinite loop starts as soon as i press a comma when typing in the "other income" sections.

**Comment by dlouise64** [comment]
@Br3nda I have done another pass on this. Added a check to see if total income is not a number. If its Nan then the state doesn't get set. Have tried to replicate error above and not getting it anymore.

**Pull request merged**
